services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - app-network

  redis:
    image: redis:7
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - app-network

  metadata:
    build:
      context: .
      dockerfile: cmd/metadata/Dockerfile
    environment:
      - GRPC_PORT=50051
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
  upload:
    build:
      context: .
      dockerfile: cmd/upload/Dockerfile
    ports:
      - "50052:50052"
    environment:
      - GRPC_PORT=50052
      - METADATA_SERVICE_ADDR=metadata:50051
      - REDIS_ADDR=redis:6379
      - UPLOAD_DIR=/app/uploads
    volumes:
      - ./data/uploads:/app/uploads
    depends_on:
      - postgres
      - redis
      - metadata
    networks:
      - app-network
  worker:
    build:
      context: .
      dockerfile: cmd/worker/Dockerfile
    environment:
      - METADATA_SERVICE_ADDR=metadata:50051
      - REDIS_ADDR=redis:6379
      - RESULT_SERVICE_ADDR=result:50053
    volumes:
      - ./data/uploads:/app/uploads
    depends_on:
      - metadata
      - redis
      - result
    networks:
      - app-network

  result:
    build:
      context: .
      dockerfile: cmd/result/Dockerfile
    ports:
      - "50053:50053"
    environment:
      - GRPC_PORT=50053
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}?sslmode=disable
      - REDIS_ADDR=redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - app-network

  grpc-ui:
    image: fullstorydev/grpcui
    container_name: grpc-ui
    environment:
      - GRPC_PORT=result:50053
    ports:
      - "8080:8080"
    command: -plaintext -bind 0.0.0.0 result:50053
    depends_on:
      - result
    networks:
      - app-network
networks:
    app-network:
      driver: bridge
