apiVersion: v1
kind: Service
metadata:
  name: upload-service
spec:
  type: NodePort
  selector:
    app: upload
  ports:
    - port: 8080        
      targetPort: 50051 
      nodePort: 30080  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload
spec:
  selector:
    matchLabels:
      app: upload
  template:
    metadata:
      labels:
        app: upload
    spec:
      containers:
      - name: upload
        image: janrusell/upload-service:v1
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: storage
          mountPath: /app/uploads
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env: 
        - name: REDIS_ADDR
          valueFrom: 
            configMapKeyRef: 
              name: shared-services-config
              key: REDIS_ADDR
        - name: METADATA_SERVICE_ADDR
          valueFrom:
            configMapKeyRef:
              name: shared-services-config
              key: METADATA_SERVICE_ADDR
        - name: UPLOAD_DIR
          valueFrom:
            configMapKeyRef:
              name: shared-services-config
              key: UPLOAD_DIR
      volumes:
      - name: storage
        persistentVolumeClaim: 
          claimName: upload-pvc